spring.application.name=Project
# MongoDB Atlas connection
spring.data.mongodb.uri=mongodb+srv://bookuser:bookpass123@cluster0.xjslic1.mongodb.net/bookdb?retryWrites=true&w=majority&appName=Cluster0

# Thymeleaf settings
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Optional - show MongoDB logs
# logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG


# === Server Port (Optional) ===
# Uncomment the next line if you want to change the port (default is 8080)
 #server.port=8081

# === Logging (Optional) ===
# Uncomment to show MongoDB queries in console
# logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

